project_id = "livingword"

[api]
port = 54321

[functions.multiply-sermon]
enabled = true
verify_jwt = false

[functions.sermon-research]
enabled = true
verify_jwt = false

[functions.get-devotional-today]
enabled = true
verify_jwt = false

[functions.track-pageview]
enabled = true
verify_jwt = false

[functions.recommend-devotional]
enabled = true
verify_jwt = false
